### PR TITLE
539 Created first draft E2E tests

### LINKED ISSUE #539: Create basic smoke e2e smoke test
#### Approach
Playwright
Look for invariants to test (things that will be true no matter the shape of the data)

Lets test:
1. Filters
2. Sorting
3. Pagination
4. Changing Entities
5. Summary count
6. We can add to this list once we get going.

#### Pagination Detail
Some items to test for pagination

- [ ] 1. Hitting a tab starts off at page 1.
- [ ] 2. After incrementing the page, the page is incremented and the data is at least different from the previous page (check the first row for example) 
- [ ] 3. You can't go back past page 1.
- [ ] 4. You can't go forward past the last page
- [ ] 5. Changing the sort sets the page back to 1.
- [ ] 6. Changing the tab sets the page back to 1

### PR DESCRIPTION
**Pull request by jpaten**
### Ticket
Closes #539 and #599.

### Reviewers
@NoopDog .

### Changes
- Wrote first draft for tests covering pagination, url routing tabs, filters, and sort. for AnVIL
- Wrote tests for tabs, url routing, and filters for AnVIL Catalog

### Known Issues
- Tests are very slow
- Probably too implementation dependent
- Reliability concerns

### CODE REVIEW

**Comment by NoopDog** [comment]
Hi, @jpaten can you rebase this on the lastest main and check the tests still pass?

Thanks, 
D

**Comment by NoopDog** [comment]
Hi @jpaten, can you add a command to run the tests to the package.json for "anvil" like `test:anvil` in the scripts section? This would set up the anvil config (similar to the `dev` commands) and then run the test or run a script that runs the test. 

Thanks!
D

**Comment by jpaten** [comment]
@NoopDog I added that command, turns out there's a config option in Playwright that makes it really easy! I also added a test for the url functionality so that can be separated out of existing ones, and attempted to debug a couple of tests that I noticed were unreliable(notably `tabs.spec.ts`) but I'm not sure if I was successful.

**Comment by NoopDog** [comment]
Thanks, @jpaten  can you rebase this again and check that the pagination works now?

**Comment by NoopDog** [comment]
Some items to test for pagination

1. Hitting a tab starts off at page 1.
2. After incrementing the page, the page is incremented and the data is at least different from the previous page (check the first row for example) 
3. You can't go back past page 1.
4. You can't go forward past the last page
5. Changing the sort sets the page back to 1.
6. Changing the tab sets the page back to 1

What else?

**Comment by jpaten** [comment]
The issues should be cleaned up now! They were all with the pagination tests since I hadn't been able to run them on a functional implementation before, I think the only other ones were with `tabs.spec.ts`. I've ran them like 20 times and never gotten an error when the page is working properly, so hopefully they're alright However, a couple of times they managed to make the page look like this. I was able to reproduce it manually by clicking onto a different tab very quickly right after the page loaded, which the tests also do. Let me know if there's anything else I need to work on!

test-failed-1

**Comment by jpaten** [comment]
Added additional tests, but AnVIL ones won't pass right now since I think there's some sort of server-side issue(the site won't load manually on my machine and I didn't change anything)

**Review by NoopDog — APPROVED** [review]

**Pull request merged**
